//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesodatosD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoDatos
    {
        public int IdAccesodatos { get; set; }
        public string Cedula { get; set; }
        public string CodigoUsuario { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
