//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ejemplo1Model", "FK_AccesoDatos_Clientes", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AccesodatosD.Clientes), "AccesoDatos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AccesodatosD.AccesoDatos), true)]

#endregion

namespace AccesodatosD
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ejemplo1Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ejemplo1Entities usando la cadena de conexión encontrada en la sección 'ejemplo1Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public ejemplo1Entities() : base("name=ejemplo1Entities", "ejemplo1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ejemplo1Entities.
        /// </summary>
        public ejemplo1Entities(string connectionString) : base(connectionString, "ejemplo1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ejemplo1Entities.
        /// </summary>
        public ejemplo1Entities(EntityConnection connection) : base(connection, "ejemplo1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<AccesoDatos> AccesoDatos
        {
            get
            {
                if ((_AccesoDatos == null))
                {
                    _AccesoDatos = base.CreateObjectSet<AccesoDatos>("AccesoDatos");
                }
                return _AccesoDatos;
            }
        }
        private ObjectSet<AccesoDatos> _AccesoDatos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet AccesoDatos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAccesoDatos(AccesoDatos accesoDatos)
        {
            base.AddObject("AccesoDatos", accesoDatos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ejemplo1Model", Name="AccesoDatos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AccesoDatos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto AccesoDatos.
        /// </summary>
        /// <param name="idAccesodatos">Valor inicial de la propiedad IdAccesodatos.</param>
        public static AccesoDatos CreateAccesoDatos(global::System.Int32 idAccesodatos)
        {
            AccesoDatos accesoDatos = new AccesoDatos();
            accesoDatos.IdAccesodatos = idAccesodatos;
            return accesoDatos;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAccesodatos
        {
            get
            {
                return _IdAccesodatos;
            }
            set
            {
                if (_IdAccesodatos != value)
                {
                    OnIdAccesodatosChanging(value);
                    ReportPropertyChanging("IdAccesodatos");
                    _IdAccesodatos = StructuralObject.SetValidValue(value, "IdAccesodatos");
                    ReportPropertyChanged("IdAccesodatos");
                    OnIdAccesodatosChanged();
                }
            }
        }
        private global::System.Int32 _IdAccesodatos;
        partial void OnIdAccesodatosChanging(global::System.Int32 value);
        partial void OnIdAccesodatosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                OnCedulaChanging(value);
                ReportPropertyChanging("Cedula");
                _Cedula = StructuralObject.SetValidValue(value, true, "Cedula");
                ReportPropertyChanged("Cedula");
                OnCedulaChanged();
            }
        }
        private global::System.String _Cedula;
        partial void OnCedulaChanging(global::System.String value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodigoUsuario
        {
            get
            {
                return _CodigoUsuario;
            }
            set
            {
                OnCodigoUsuarioChanging(value);
                ReportPropertyChanging("CodigoUsuario");
                _CodigoUsuario = StructuralObject.SetValidValue(value, true, "CodigoUsuario");
                ReportPropertyChanged("CodigoUsuario");
                OnCodigoUsuarioChanged();
            }
        }
        private global::System.String _CodigoUsuario;
        partial void OnCodigoUsuarioChanging(global::System.String value);
        partial void OnCodigoUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value, "FechaRegistro");
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaRegistro;
        partial void OnFechaRegistroChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, "Estado");
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Estado;
        partial void OnEstadoChanging(Nullable<global::System.Boolean> value);
        partial void OnEstadoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ejemplo1Model", "FK_AccesoDatos_Clientes", "Clientes")]
        public Clientes Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ejemplo1Model.FK_AccesoDatos_Clientes", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ejemplo1Model.FK_AccesoDatos_Clientes", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("ejemplo1Model.FK_AccesoDatos_Clientes", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clientes>("ejemplo1Model.FK_AccesoDatos_Clientes", "Clientes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ejemplo1Model", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Clientes.
        /// </summary>
        /// <param name="cedula">Valor inicial de la propiedad Cedula.</param>
        public static Clientes CreateClientes(global::System.String cedula)
        {
            Clientes clientes = new Clientes();
            clientes.Cedula = cedula;
            return clientes;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                if (_Cedula != value)
                {
                    OnCedulaChanging(value);
                    ReportPropertyChanging("Cedula");
                    _Cedula = StructuralObject.SetValidValue(value, false, "Cedula");
                    ReportPropertyChanged("Cedula");
                    OnCedulaChanged();
                }
            }
        }
        private global::System.String _Cedula;
        partial void OnCedulaChanging(global::System.String value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, true, "Apellido");
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true, "Direccion");
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true, "Telefono");
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ejemplo1Model", "FK_AccesoDatos_Clientes", "AccesoDatos")]
        public EntityCollection<AccesoDatos> AccesoDatos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AccesoDatos>("ejemplo1Model.FK_AccesoDatos_Clientes", "AccesoDatos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AccesoDatos>("ejemplo1Model.FK_AccesoDatos_Clientes", "AccesoDatos", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
